FROM registry.cn-beijing.aliyuncs.com/fancyflip/openjdk:17

# 设置应用目录
ARG APP_HOME="fancy-app-servers"
ARG APP_NAME="fancy-agent-app"

# 设置环境变量
ENV JAVA_OPTS="\
    -server \
    -Xmx1344m \
    -Xms1344m \
    -Xmn448m \
    -XX:MaxMetaspaceSize=192M \
    -XX:MetaspaceSize=192M "


# 设置工作目录
WORKDIR /app

# 复制 JAR 文件到容器中
COPY ${APP_HOME}/${APP_NAME}/target/*.jar /app/app.jar

# 设置入口点
ENTRYPOINT java ${JAVA_OPTS} -Djava.security.egd=file:/dev/./urandom -jar app.jar --spring.profiles.active=prod